/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wamp.vistas;

import actualizacionwamp.entity.Acudientes;
import actualizacionwamp.entity.Usuario;
import actualizacionwamp.httpclient;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Arleys
 */
public class Home extends javax.swing.JFrame {
public Usuario uActual;    
DefaultListModel modelo = new DefaultListModel();
    /**
     * Creates new form Home
     */
 

    Home() {
     initComponents();
     jList1.setModel(modelo);
     
    }

    Home(Usuario flag) {
        initComponents();
        jList1.setModel(modelo);
        this.uActual=flag;
        lbl_usuarioActual.setText(uActual.getNOMBRE());
       listarAcudientes(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_background = new javax.swing.JPanel();
        panel_datousuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_usuarioActual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        panel_funciones = new javax.swing.JPanel();
        btn_alerta_bradcast = new javax.swing.JButton();
        btn_alertaDirigida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_background.setBackground(new java.awt.Color(255, 255, 255));

        panel_datousuarios.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WAMP");

        lbl_usuarioActual.setText("anonimo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Where Are My People");

        btn_Salir.setBackground(new java.awt.Color(0, 204, 204));
        btn_Salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(255, 0, 51));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_datousuariosLayout = new javax.swing.GroupLayout(panel_datousuarios);
        panel_datousuarios.setLayout(panel_datousuariosLayout);
        panel_datousuariosLayout.setHorizontalGroup(
            panel_datousuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datousuariosLayout.createSequentialGroup()
                .addGroup(panel_datousuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datousuariosLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(panel_datousuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_usuarioActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datousuariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Salir))
            .addGroup(panel_datousuariosLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_datousuariosLayout.setVerticalGroup(
            panel_datousuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datousuariosLayout.createSequentialGroup()
                .addComponent(btn_Salir)
                .addGap(35, 35, 35)
                .addGroup(panel_datousuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panel_datousuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_usuarioActual))
                .addContainerGap())
        );

        panel_funciones.setBackground(new java.awt.Color(255, 255, 255));
        panel_funciones.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255)));

        btn_alerta_bradcast.setBackground(new java.awt.Color(204, 255, 255));
        btn_alerta_bradcast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_alerta_bradcast.setText("Alerta rápida");
        btn_alerta_bradcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alerta_bradcastActionPerformed(evt);
            }
        });

        btn_alertaDirigida.setText("Alertar a: ");
        btn_alertaDirigida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alertaDirigidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_funcionesLayout = new javax.swing.GroupLayout(panel_funciones);
        panel_funciones.setLayout(panel_funcionesLayout);
        panel_funcionesLayout.setHorizontalGroup(
            panel_funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_funcionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_alertaDirigida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alerta_bradcast, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel_funcionesLayout.setVerticalGroup(
            panel_funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_funcionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_alerta_bradcast, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_alertaDirigida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Mis contactos: ");

        btn_add.setBackground(new java.awt.Color(204, 255, 255));
        btn_add.setText("Añadir acudiente");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_backgroundLayout = new javax.swing.GroupLayout(panel_background);
        panel_background.setLayout(panel_backgroundLayout);
        panel_backgroundLayout.setHorizontalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panel_funciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panel_backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_add)))
                .addContainerGap())
            .addComponent(panel_datousuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_backgroundLayout.setVerticalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addComponent(panel_datousuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_backgroundLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(panel_funciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alerta_bradcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alerta_bradcastActionPerformed
        String i=Integer.toString(uActual.getID());
        generarAlertaBroadcast(i);
        JOptionPane.showMessageDialog(this, "HAS GENERADO UNA ALERTA");
    }//GEN-LAST:event_btn_alerta_bradcastActionPerformed

    private void btn_alertaDirigidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alertaDirigidaActionPerformed
       String i=Integer.toString(uActual.getID());
       
        generarAlertaDirigida(i);
    }//GEN-LAST:event_btn_alertaDirigidaActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        VentanaRegistroAcudiente vRA= new VentanaRegistroAcudiente();
        vRA.setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
    this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_alertaDirigida;
    public static javax.swing.JButton btn_alerta_bradcast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_usuarioActual;
    private javax.swing.JPanel panel_background;
    private javax.swing.JPanel panel_datousuarios;
    private javax.swing.JPanel panel_funciones;
    // End of variables declaration//GEN-END:variables

    private void generarAlertaBroadcast(String usuarioActual) {
        try {
            List<String> listaCorreos=new ArrayList();
            //llenar lista con los contactos del usuario:
            
            String n=String.valueOf(listaCorreos.size());
            httpclient.sendPOST_EnviarNotificacion(n,listaCorreos);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarAlertaDirigida(String usuarioActual) {
       String s=JOptionPane.showInputDialog(this,"Correo del destinatario");
        JOptionPane.showMessageDialog(this, "Has Alertado a: "+s);
    }

    private void listarAcudientes(){
    try {
        String idActual;
        System.out.println("Uactual id"+ uActual.getID());
        idActual = Integer.toString(uActual.getID());
        ArrayList<Acudientes> lista=new ArrayList<>(httpclient.sendPOST_ObtenerAcudienteUsuario(idActual));
        System.out.println("ListaAcudiente: "+lista);
        ArrayList listaNombres=new ArrayList();
        for (Acudientes acudientes : lista) {
            listaNombres.add(acudientes.getEmail());
        }
        modelo.addElement(listaNombres);
    } catch (IOException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    } 
    
}
